# Tidy data

In [ ]:

import os
from google.colab import files

import pandas as pd
import altair as alt
import numpy as np
import io
from google.colab import data_table
import datetime
from pandas.tseries.offsets import Day

data_table.enable_dataframe_formatter()

In [ ]:
#upload file
uploaded = files.upload()
df = pd.read_csv(io.BytesIO(uploaded['MAIN_all_lakes_zstats_S2_jrc50_19-21_1.csv']))

#drop unneeded cols
df = df.iloc[0:, 2:]
df = df.drop(['AreaSqKm', 'COUNTY_Nam', 'COUNTY_Zon', 'ComID', 'EDU_Name', 'EDU_ZoneID', 'Elevation', 'FCode','FDate','FType','GNIS_ID','GNIS_Name','HU12','HU12_Name','HU12_ZoneI','HU4','HU4_Name','HU4_ZoneID','HU6','HU6_Name',
              'HU6_ZoneID','HU8','HU8_Name','HU8_ZoneID','LakeConnec','Lake_Area_','Permanent_','ReachCode','STATE','STATE_Zone','State_Name'],axis=1)

#wide to long
test = df.melt(['lagoslakei'], var_name = "imageID", value_name = "values")
#drop nas
test = test.dropna()

#split imageID into col variables
test[["satellite", "date", "delete_date", "tile", "band"]] = test["imageID"].str.split('_', expand=True)
test = test.drop(['delete_date', 'imageID'], axis=1)
test[["capture_date", "delete"]] = test["date"].str.split('T', expand=True)
test = test.drop(['date', 'delete'], axis=1)
#format date
test["capture_date"] = pd.to_datetime(test["capture_date"], format='%Y%m%d')

#remove duplicates
test = test.drop_duplicates(keep='first')

#long to wide format
test = test.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test, num_rows_per_page=10)

In [ ]:
#upload file
uploaded2 = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded2['MAIN_all_lakes_zstats_S2_jrc50_22-23_1.csv']))

#drop unneeded cols
df2 = df2.iloc[0:, 2:]
df2 = df2.drop(['AreaSqKm', 'COUNTY_Nam', 'COUNTY_Zon', 'ComID', 'EDU_Name', 'EDU_ZoneID', 'Elevation', 'FCode','FDate','FType','GNIS_ID','GNIS_Name','HU12','HU12_Name','HU12_ZoneI','HU4','HU4_Name','HU4_ZoneID','HU6','HU6_Name',
              'HU6_ZoneID','HU8','HU8_Name','HU8_ZoneID','LakeConnec','Lake_Area_','Permanent_','ReachCode','STATE','STATE_Zone','State_Name'],axis=1)

#wide to long
test2 = df2.melt(['lagoslakei'], var_name = "imageID", value_name = "values")
#drop nas
test2 = test2.dropna()

#split imageID into col variables
test2[["satellite", "date", "delete_date", "tile", "band"]] = test2["imageID"].str.split('_', expand=True)
test2 = test2.drop(['delete_date', 'imageID'], axis=1)
test2[["capture_date", "delete"]] = test2["date"].str.split('T', expand=True)
test2 = test2.drop(['date', 'delete'], axis=1)
#format date
test2["capture_date"] = pd.to_datetime(test2["capture_date"], format='%Y%m%d')

#remove duplicates
test2 = test2.drop_duplicates(keep='first')

#long to wide format
test2 = test2.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test2, num_rows_per_page=10)

In [ ]:
#upload file
uploaded3 = files.upload()
df3 = pd.read_csv(io.BytesIO(uploaded3['MAIN_all_lakes_zstats_S2_jrc50_19-21_2.csv']))

#drop unneeded cols
df3 = df3.iloc[0:, 2:]
df3 = df3.drop(['AreaSqKm', 'COUNTY_Nam', 'COUNTY_Zon', 'ComID', 'EDU_Name', 'EDU_ZoneID', 'Elevation', 'FCode','FDate','FType','GNIS_ID','GNIS_Name','HU12','HU12_Name','HU12_ZoneI','HU4','HU4_Name','HU4_ZoneID','HU6','HU6_Name',
              'HU6_ZoneID','HU8','HU8_Name','HU8_ZoneID','LakeConnec','Lake_Area_','Permanent_','ReachCode','STATE','STATE_Zone','State_Name'],axis=1)

#wide to long
test3 = df3.melt(['lagoslakei'], var_name = "imageID", value_name = "values")
#drop nas
test3 = test3.dropna()

#split imageID into col variables
test3[["satellite", "date", "delete_date", "tile", "band"]] = test3["imageID"].str.split('_', expand=True)
test3 = test3.drop(['delete_date', 'imageID'], axis=1)
test3[["capture_date", "delete"]] = test3["date"].str.split('T', expand=True)
test3 = test3.drop(['date', 'delete'], axis=1)
#format date
test3["capture_date"] = pd.to_datetime(test3["capture_date"], format='%Y%m%d')

#remove duplicates
test3 = test3.drop_duplicates(keep='first')

#long to wide format
test3 = test3.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test3, num_rows_per_page=10)

In [ ]:
#upload file
# uploaded4 = files.upload()
df4 = pd.read_csv(io.BytesIO(uploaded4['MAIN_all_lakes_zstats_S2_jrc50_22-23_2.csv']))

#drop unneeded cols
df4 = df4.iloc[0:, 2:]
df4 = df4.drop(['AreaSqKm', 'COUNTY_Nam', 'COUNTY_Zon', 'ComID', 'EDU_Name', 'EDU_ZoneID', 'Elevation', 'FCode','FDate','FType','GNIS_ID','GNIS_Name','HU12','HU12_Name','HU12_ZoneI','HU4','HU4_Name','HU4_ZoneID','HU6','HU6_Name',
              'HU6_ZoneID','HU8','HU8_Name','HU8_ZoneID','LakeConnec','Lake_Area_','Permanent_','ReachCode','STATE','STATE_Zone','State_Name'],axis=1)

#wide to long
test4 = df4.melt(['lagoslakei'], var_name = "imageID", value_name = "values")
#drop nas
test4 = test4.dropna()

#split imageID into col variables
test4[["satellite", "date", "delete_date", "tile", "band"]] = test4["imageID"].str.split('_', expand=True)
test4 = test4.drop(['delete_date', 'imageID'], axis=1)
test4[["capture_date", "delete"]] = test4["date"].str.split('T', expand=True)
test4 = test4.drop(['date', 'delete'], axis=1)
#format date
test4["capture_date"] = pd.to_datetime(test4["capture_date"], format='%Y%m%d')

#remove duplicates
test4 = test4.drop_duplicates(keep='first')

#long to wide format
test4 = test4.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test4, num_rows_per_page=10)

In [ ]:
#upload file
uploaded5 = files.upload()
df5 = pd.read_csv(io.BytesIO(uploaded5['MAIN_all_lakes_zstats_S2_jrc50_19-21_3.csv']))

#drop unneeded cols
df5 = df5.iloc[0:, 2:]
df5 = df5.drop(['AreaSqKm', 'COUNTY_Nam', 'COUNTY_Zon', 'ComID', 'EDU_Name', 'EDU_ZoneID', 'Elevation', 'FCode','FDate','FType','GNIS_ID','GNIS_Name','HU12','HU12_Name','HU12_ZoneI','HU4','HU4_Name','HU4_ZoneID','HU6','HU6_Name',
              'HU6_ZoneID','HU8','HU8_Name','HU8_ZoneID','LakeConnec','Lake_Area_','Permanent_','ReachCode','STATE','STATE_Zone','State_Name'],axis=1)

#wide to long
test5 = df5.melt(['lagoslakei'], var_name = "imageID", value_name = "values")
#drop nas
test5 = test5.dropna()

#split imageID into col variables
test5[["satellite", "date", "delete_date", "tile", "band"]] = test5["imageID"].str.split('_', expand=True)
test5 = test5.drop(['delete_date', 'imageID'], axis=1)
test5[["capture_date", "delete"]] = test5["date"].str.split('T', expand=True)
test5 = test5.drop(['date', 'delete'], axis=1)
#format date
test5["capture_date"] = pd.to_datetime(test5["capture_date"], format='%Y%m%d')

#remove duplicates
test5 = test5.drop_duplicates(keep='first')

#long to wide format
test5 = test5.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test5, num_rows_per_page=10)

In [ ]:
#upload file
uploaded6 = files.upload()
df6 = pd.read_csv(io.BytesIO(uploaded6['MAIN_all_lakes_zstats_S2_jrc50_22-23_3.csv']))

#drop unneeded cols
df6 = df6.iloc[0:, 2:]
df6 = df6.drop(['AreaSqKm', 'COUNTY_Nam', 'COUNTY_Zon', 'ComID', 'EDU_Name', 'EDU_ZoneID', 'Elevation', 'FCode','FDate','FType','GNIS_ID','GNIS_Name','HU12','HU12_Name','HU12_ZoneI','HU4','HU4_Name','HU4_ZoneID','HU6','HU6_Name',
              'HU6_ZoneID','HU8','HU8_Name','HU8_ZoneID','LakeConnec','Lake_Area_','Permanent_','ReachCode','STATE','STATE_Zone','State_Name'],axis=1)

#wide to long
test6 = df6.melt(['lagoslakei'], var_name = "imageID", value_name = "values")
#drop nas
test6 = test6.dropna()

#split imageID into col variables
test6[["satellite", "date", "delete_date", "tile", "band"]] = test6["imageID"].str.split('_', expand=True)
test6 = test6.drop(['delete_date', 'imageID'], axis=1)
test6[["capture_date", "delete"]] = test6["date"].str.split('T', expand=True)
test6 = test6.drop(['date', 'delete'], axis=1)
#format date
test6["capture_date"] = pd.to_datetime(test6["capture_date"], format='%Y%m%d')

#remove duplicates
test6 = test6.drop_duplicates(keep='first')

#long to wide format
test6 = test6.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test6, num_rows_per_page=10)

In [ ]:
#upload file
# uploaded7 = files.upload()
df7 = pd.read_csv(io.BytesIO(uploaded7['MAIN_all_lakes_zstats_S2_jrc50_19-21_4a.csv']))

#drop unneeded cols
df7 = df7.iloc[0:, 2:]
df7 = df7.drop(['AreaSqKmS2a', 'COUNTY_NamS2a', 'COUNTY_ZonS2a', 'ComIDS2a', 'EDU_NameS2a', 'EDU_ZoneIDS2a', 'ElevationS2a', 'FCodeS2a','FDateS2a','FTypeS2a','GNIS_IDS2a','GNIS_NameS2a','HU12S2a','HU12_NameS2a','HU12_ZoneIS2a','HU4S2a','HU4_NameS2a',
                'HU4_ZoneIDS2a','HU6S2a','HU6_NameS2a','HU6_ZoneIDS2a','HU8S2a','HU8_NameS2a','HU8_ZoneIDS2a','LakeConnecS2a','Lake_Area_S2a','Permanent_S2a','ReachCodeS2a','STATES2a','STATE_ZoneS2a','State_NameS2a',
                'geometryS2b','AreaSqKmS2b', 'COUNTY_NamS2b', 'COUNTY_ZonS2b', 'ComIDS2b', 'EDU_NameS2b', 'EDU_ZoneIDS2b', 'ElevationS2b', 'FCodeS2b','FDateS2b','FTypeS2b','GNIS_IDS2b','GNIS_NameS2b','HU12S2b','HU12_NameS2b','HU12_ZoneIS2b','HU4S2b',
                'HU4_NameS2b','HU4_ZoneIDS2b','HU6S2b','HU6_NameS2b','HU6_ZoneIDS2b','HU8S2b','HU8_NameS2b','HU8_ZoneIDS2b','LakeConnecS2b','Lake_Area_S2b','Permanent_S2b','ReachCodeS2b','STATES2b','STATE_ZoneS2b','State_NameS2b'],axis=1)

#wide to long
test7 = df7.melt(['lagoslakeiS2a','lagoslakeiS2b'], var_name = "imageID", value_name = "values")
test7 = test7.drop(['lagoslakeiS2b'],axis=1)
#rename cols
test7 = test7.rename(columns={"lagoslakeiS2a":"lagoslakei"})
#drop nas
test7 = test7.dropna()

#split imageID into col variables
test7[["date", "delete_date", "tile", "band"]] = test7["imageID"].str.split('_', expand=True)
test7 = test7.drop(['delete_date', 'imageID'], axis=1)
test7[["capture_date", "delete"]] = test7["date"].str.split('T', expand=True)
test7 = test7.drop(['date', 'delete'], axis=1)
test7[['satellite']] = 1
#format date
test7["capture_date"] = pd.to_datetime(test7["capture_date"], format='%Y%m%d')

#remove duplicates
test7 = test7.drop_duplicates(keep='first')

#long to wide format
test7 = test7.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()


#display
data_table.DataTable(test7, num_rows_per_page=10)

In [ ]:
#upload file
# uploaded8 = files.upload()
df8 = pd.read_csv(io.BytesIO(uploaded8['MAIN_all_lakes_zstats_S2_jrc50_19-21_4b.csv']))

#drop unneeded cols
df8 = df8.iloc[0:, 2:]
df8 = df8.drop(['AreaSqKmS2a', 'COUNTY_NamS2a', 'COUNTY_ZonS2a', 'ComIDS2a', 'EDU_NameS2a', 'EDU_ZoneIDS2a', 'ElevationS2a', 'FCodeS2a','FDateS2a','FTypeS2a','GNIS_IDS2a','GNIS_NameS2a','HU12S2a','HU12_NameS2a','HU12_ZoneIS2a','HU4S2a','HU4_NameS2a',
                'HU4_ZoneIDS2a','HU6S2a','HU6_NameS2a','HU6_ZoneIDS2a','HU8S2a','HU8_NameS2a','HU8_ZoneIDS2a','LakeConnecS2a','Lake_Area_S2a','Permanent_S2a','ReachCodeS2a','STATES2a','STATE_ZoneS2a','State_NameS2a',
                'geometryS2b','AreaSqKmS2b', 'COUNTY_NamS2b', 'COUNTY_ZonS2b', 'ComIDS2b', 'EDU_NameS2b', 'EDU_ZoneIDS2b', 'ElevationS2b', 'FCodeS2b','FDateS2b','FTypeS2b','GNIS_IDS2b','GNIS_NameS2b','HU12S2b','HU12_NameS2b','HU12_ZoneIS2b','HU4S2b',
                'HU4_NameS2b','HU4_ZoneIDS2b','HU6S2b','HU6_NameS2b','HU6_ZoneIDS2b','HU8S2b','HU8_NameS2b','HU8_ZoneIDS2b','LakeConnecS2b','Lake_Area_S2b','Permanent_S2b','ReachCodeS2b','STATES2b','STATE_ZoneS2b','State_NameS2b'],axis=1)

#wide to long
test8 = df8.melt(['lagoslakeiS2a','lagoslakeiS2b'], var_name = "imageID", value_name = "values")
test8 = test8.drop(['lagoslakeiS2b'],axis=1)
#rename cols
test8 = test8.rename(columns={"lagoslakeiS2a":"lagoslakei"})
#drop nas
test8 = test8.dropna()

#split imageID into col variables
test8[["date", "delete_date", "tile", "band"]] = test8["imageID"].str.split('_', expand=True)
test8 = test8.drop(['delete_date', 'imageID'], axis=1)
test8[["capture_date", "delete"]] = test8["date"].str.split('T', expand=True)
test8 = test8.drop(['date', 'delete'], axis=1)
test8[['satellite']] = 1
#format date
test8["capture_date"] = pd.to_datetime(test8["capture_date"], format='%Y%m%d')

#remove duplicates
test8 = test8.drop_duplicates(keep='first')

#long to wide format
test8 = test8.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test8, num_rows_per_page=10)

In [ ]:
#upload file
uploaded9 = files.upload()
df9 = pd.read_csv(io.BytesIO(uploaded9['MAIN_all_lakes_zstats_S2_jrc50_22-23_4.csv']))

#drop unneeded cols
df9 = df9.iloc[0:, 2:]
df9 = df9.drop(['AreaSqKmS2a', 'COUNTY_NamS2a', 'COUNTY_ZonS2a', 'ComIDS2a', 'EDU_NameS2a', 'EDU_ZoneIDS2a', 'ElevationS2a', 'FCodeS2a','FDateS2a','FTypeS2a','GNIS_IDS2a','GNIS_NameS2a','HU12S2a','HU12_NameS2a','HU12_ZoneIS2a','HU4S2a','HU4_NameS2a',
                'HU4_ZoneIDS2a','HU6S2a','HU6_NameS2a','HU6_ZoneIDS2a','HU8S2a','HU8_NameS2a','HU8_ZoneIDS2a','LakeConnecS2a','Lake_Area_S2a','Permanent_S2a','ReachCodeS2a','STATES2a','STATE_ZoneS2a','State_NameS2a',
                'geometryS2b','AreaSqKmS2b', 'COUNTY_NamS2b', 'COUNTY_ZonS2b', 'ComIDS2b', 'EDU_NameS2b', 'EDU_ZoneIDS2b', 'ElevationS2b', 'FCodeS2b','FDateS2b','FTypeS2b','GNIS_IDS2b','GNIS_NameS2b','HU12S2b','HU12_NameS2b','HU12_ZoneIS2b','HU4S2b',
                'HU4_NameS2b','HU4_ZoneIDS2b','HU6S2b','HU6_NameS2b','HU6_ZoneIDS2b','HU8S2b','HU8_NameS2b','HU8_ZoneIDS2b','LakeConnecS2b','Lake_Area_S2b','Permanent_S2b','ReachCodeS2b','STATES2b','STATE_ZoneS2b','State_NameS2b'],axis=1)

#wide to long
test9 = df9.melt(['lagoslakeiS2a','lagoslakeiS2b'], var_name = "imageID", value_name = "values")
test9 = test9.drop(['lagoslakeiS2b'],axis=1)
#rename cols
test9 = test9.rename(columns={"lagoslakeiS2a":"lagoslakei"})
#drop nas
test9 = test9.dropna()

#split imageID into col variables
test9[["date", "delete_date", "tile", "band"]] = test9["imageID"].str.split('_', expand=True)
test9 = test9.drop(['delete_date', 'imageID'], axis=1)
test9[["capture_date", "delete"]] = test9["date"].str.split('T', expand=True)
test9 = test9.drop(['date', 'delete'], axis=1)
test9[['satellite']] = 1
#format date
test9["capture_date"] = pd.to_datetime(test9["capture_date"], format='%Y%m%d')

#remove duplicates
test9 = test9.drop_duplicates(keep='first')

#long to wide format
test9 = test9.pivot_table(values='values',
                        index=['lagoslakei', 'satellite', 'tile', 'capture_date'],
                        columns=['band'],
                        aggfunc='mean').reset_index()

#display
data_table.DataTable(test9, num_rows_per_page=10)

In [ ]:
#join dfs
combined_df = pd.concat([test,test,test3,test4,test5,test6,test7,test8,test9]).sort_values(by=['lagoslakei'])

#remove NAs
combined_df = combined_df.dropna()

#display
data_table.DataTable(combined_df, num_rows_per_page=10)

In [ ]:
out_dir = os.path.expanduser('~/Downloads')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)

output_filepath = os.path.join(out_dir, 'sentinel_allLakes_jrc50.csv')
combined_df.to_csv(output_filepath)